services:
  backend:
    build: ./snm-backend
    image: smoke-and-murders/backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AllowedOrigins=${ALLOWED_ORIGINS}
    ports:
      - ${BACKEND_PORT}:8080

  frontend:
    build:
      context: ./snm-frontend
      args:
        - NEXT_PUBLIC_API_HOST=${NEXT_PUBLIC_API_HOST}
        - NEXT_PUBLIC_API_PORT=${NEXT_PUBLIC_API_PORT}
    image: smoke-and-murders/frontend
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT}:3000